### ISSUE TITLE
Error when compiling "InnoDefaultRenderingClient"

### ISSUE THREAD

**Issue by QuentinTessier** [zhangdoa/InnocenceEngine#14]
I'm trying to compile InnocenceEngine, I'm having trouble with the last commit on linux.
In  Source/Engine/Common/InnoGraphicsPrimitive.h:
![commit f54a3175d5bc14688ea1a460755c938773846ee5](https://user-images.githubusercontent.com/35849299/84123746-8c7c4180-aa3a-11ea-8b3f-4603a1a9c564.PNG)
When compiling:
![InnoCompileError](https://user-images.githubusercontent.com/35849299/84124667-d1ed3e80-aa3b-11ea-9220-7006dab290b5.png)
Removing the line throwing the errors fix the problem.

**Comment by zhangdoa** [comment]
Hello @QuentinTessier,

The bug has been fixed in 9921bef, please check if it works.

**Comment by QuentinTessier** [comment]
It's fixed, thanks.
