### ISSUE TITLE
Error when compiling on linux

### ISSUE THREAD

**Issue by DraGiuS** [zhangdoa/InnocenceEngine#9]
Hi,
here the output : 

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

Please set them or make sure they are set and tested correctly in the CMake files:
ASSIMP
 linked by target "InnoSystem" in directory /home/cristobal/Github/InnocenceEngine/source/engine/system
GLFW
    linked by target "InnoSystem" in directory /home/cristobal/Github/InnocenceEngine/source/engine/system

-- Configuring incomplete, errors occurred!
See also "/home/cristobal/Github/InnocenceEngine/build/CMakeFiles/CMakeOutput.log".
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ASSIMP
    linked by target "InnoSystem" in directory /home/cristobal/Github/InnocenceEngine/source/engine/system
GLFW
    linked by target "InnoSystem" in directory /home/cristobal/Github/InnocenceEngine/source/engine/system

-- Configuring incomplete, errors occurred!

**Comment by zhangdoa** [comment]
Hi @DraGiuS ,

Please make sure you've fully pulled the LFS files, and used the build bash script to build the project. I only tested on Ubuntu 18.04 LTS currently, so if it's still impossible to build, please tell me your Linux distribution and maybe I could do more investigation.

Thanks.

**Comment by DraGiuS** [comment]
What are the lfs files ?

**Comment by zhangdoa** [comment]
Please refer to https://git-lfs.github.com for further information about Git LFS, also you could check if the source\external\lib\unix has actual libs there rather than some fairly small (~1kb) placeholder files.

**Comment by DraGiuS** [comment]
After installing git lfs and trying to building, still the same error :'

**Comment by DraGiuS** [comment]
On gentoo

**Comment by zhangdoa** [comment]
Sorry, I'm not familiar with Gentoo, the problem should relate to the find_library() function of CMake, if you want you could try to put Assimp and GLFW libs to your system lib location and see if it works, or try to use CMake's message() to debug. My development roadmap is most on Windows so the Linux support is quite limited and still WIP.

**Comment by DraGiuS** [comment]
With your update, it now works !
